print("Welcome to the Band Name Generator.")
cityName = input("What's name of the city you grew up in?\n")
petName = input("What's your pet's name?\n")
print(f"Your band name could be {cityName} {petName}!")
print(f"Your band name could be {cityName} {petName}")
